config/routes.rb
Rails.application.routes.draw do
  root 'administrative#index'

  # Nested routes para painel administrativo
  namespace :administrative do
    resources :admins
    resources :recipes
  end

  # Redirecionamento de rotas do devise para administrador
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    confirmations: 'admins/confirmations'
  }

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :destroy
    accepts_nested_attributes_for :ingredients, reject_if: ->(attributes){ attributes['name'].blank? }, allow_destroy: true

    monetize :price_cents
end

app/controllers/administrative/admins_controller.rb
class Administrative::AdminsController < AdministrativeController
    before_action :set_admin, only: [:show, :edit, :update, :destroy]
  
    def index
      @admins = Admin.all
    end
  
    def show
    end
  
    def new
      @admin = Admin.new
    end
  
    def edit
    end
  
    def create
      @admin = Admin.new(admin_params)
  
      respond_to do |format|
        if @admin.save
          format.html { redirect_to administrative_admins_path, notice: 'Administrador criado com sucesso.' }
          format.json { render :show, status: :created, location: @admin }
        else
          format.html { render :new }
          format.json { render json: @admin.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @admin.update(admin_params)
          format.html { redirect_to administrative_admins_path, notice: 'Administrador atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @admin }
        else
          format.html { render :edit }
          format.json { render json: @admin.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @admin.destroy
      respond_to do |format|
        format.html { redirect_to administrative_admins_path, notice: 'Administrador excluido com sucesso.' }
        format.json { head :no_content }
      end
    end
  
    private

      def set_admin
        @admin = Admin.find(params[:id])
      end
  
      def admin_params
        params.require(:admin).permit(:email)
      end
  end
  

app/controllers/administrative/recipes_controller.rb
class Administrative::RecipesController < AdministrativeController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  
    def index
      @recipes = Recipe.all
    end
  
    def show
    end
  
    def new
      @recipe = Recipe.new
    end
  
    def edit
    end
  
    def create
      @recipe = Recipe.new(recipe_params)
  
      respond_to do |format|
        if @recipe.save
          format.html { redirect_to administrative_recipes_path, notice: 'Receita criada com sucesso.' }
          format.json { render :show, status: :created, location: @recipe }
        else
          format.html { render :new }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @recipe.update(recipe_params)
          format.html { redirect_to administrative_recipes_path, notice: 'Receita atualizada com sucesso.' }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @recipe.destroy
      respond_to do |format|
        format.html { redirect_to administrative_recipes_path, notice: 'Receita excluida com sucesso.' }
        format.json { head :no_content }
      end
    end
  
    private

      def set_recipe
        @recipe = Recipe.find(params[:id])
      end
  
      def recipe_params
        params.require(:recipe).permit(:name, :description, :price,
        ingredients_attributes: Ingredient.attribute_names.map(&:to_sym).push(:_destroy))
      end
  end
  

app/controllers/administrative_controller.rb
class AdministrativeController < ActionController::Base
    before_action :authenticate_admin!
    layout 'administrative'
    
    def index
    end
end

app/views/administrative/recipes/_form.html.erb
<%= form_with model: [:administrative, resource], local: true do |f|%>
<%= render partial: "administrative/shared/error_messages", locals: {resource: resource} %>

<div class="col-lg-12">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true, class: "form-control form-resource" %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <%= f.label :price %>
                <%= f.text_field :price, class: "form-control form-resource money-mask" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control form-resource" %>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="row">
            <%= link_to_add_association '+ Ingrediente', f, :ingredients, class: "btn btn-primary", data: { association_insertion_node: ".ingredients", association_insertion_method: :append } %>
        </div>
        <table class="table">
            <tbody class="ingredients has_many_table">
                <%= f.fields_for :ingredients do |ingredient| %>
                    <%= render partial: "administrative/recipes/ingredient_fields", locals: { f: ingredient } %>
                <% end %>
            </tbody>
        </table>
    </div>

    <%= f.submit "Salvar Receita", class: "btn btn-primary" %>
</div>

<% end %>

app/views/administrative/recipes/_ingredient_fields.html.erb
<tr class="nested-fields">
	<td>
		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
                    <%= f.text_field :name, placeholder: 'Nome', class: "form-control form-resource" %>
                </div>
			</div>
            <div class="col-md-4">
				<div class="form-group">
                    <%= f.number_field :quantity, placeholder: 'Qtde', class: "form-control form-resource", min: 0 %>
                </div>
			</div>
			<div class="col-md-4">
				<%= link_to_remove_association "Remover", f, class: "remove_fields btn btn-danger", data: { confirm: 'Tem certeza?'} %>
			</div>
		</div>
	</td>
</tr>

app/views/administrative/recipes/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="ibox">
                <div class="ibox-title">
                    <h2>Editar Receita</h2>
                </div>
                <div class="ibox-content">
                    <%= render partial: "administrative/recipes/form", locals: {resource: @recipe} %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/administrative/recipes/index.html.erb
<%= render partial: "administrative/shared/index_heading", 
locals: {title: "Receitas", button_title: "Nova Receita", link: new_administrative_recipe_path} %>

<div class="col-lg-12">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="datatable table table-striped table-bordered table-hover" style="width: 100%">
                    <thead>
                    <tr>   
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Preço</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @recipes.each do |recipe| %>
                    <tr>
                        <td><%= recipe.id %></td>
                        <td><%= recipe.name %></td>
                        <td><%= recipe.price %></td>
                        <td>
                            <%= link_to edit_administrative_recipe_path(recipe), class: "btn btn-info btn-circle" do %>
                                <i class="fa fa-pencil"></i>
                            <% end %>
                            
                            <%= link_to administrative_recipe_path(recipe), method: :delete, data: {confirm: "Tem certeza?"}, class: "btn btn-danger btn-circle" do %>
                                <i class="fa fa-times"></i>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/administrative/recipes/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="ibox">
                <div class="ibox-title">
                    <h2>Nova Receita</h2>
                </div>
                <div class="ibox-content">
                    <%= render partial: "administrative/recipes/form", locals: {resource: @recipe} %>
                </div>
            </div>
        </div>
    </div>
</div>