config/routes.rb
Rails.application.routes.draw do
  root 'administrative#index'

  # Nested routes para painel administrativo
  namespace :administrative do
    resources :admins
    resources :recipes
  end

  # Redirecionamento de rotas do devise para administrador
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
    confirmations: 'admins/confirmations'
  }

end

app/controllers/administrative/admins_controller.rb
class Administrative::AdminsController < AdministrativeController
    before_action :set_admin, only: [:show, :edit, :update, :destroy]
  
    def index
      @admins = Admin.all
    end
  
    def show
    end
  
    def new
      @admin = Admin.new
    end
  
    def edit
    end
  
    def create
      @admin = Admin.new(admin_params)
  
      respond_to do |format|
        if @admin.save
          format.html { redirect_to administrative_admins_path, notice: 'Administrador criado com sucesso.' }
          format.json { render :show, status: :created, location: @admin }
        else
          format.html { render :new }
          format.json { render json: @admin.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @admin.update(admin_params)
          format.html { redirect_to administrative_admins_path, notice: 'Administrador atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @admin }
        else
          format.html { render :edit }
          format.json { render json: @admin.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @admin.destroy
      respond_to do |format|
        format.html { redirect_to administrative_admins_path, notice: 'Administrador excluido com sucesso.' }
        format.json { head :no_content }
      end
    end
  
    private

      def set_admin
        @admin = Admin.find(params[:id])
      end
  
      def admin_params
        params.require(:admin).permit(:email)
      end
  end
  

app/controllers/administrative/recipes_controller.rb
class Administrative::RecipesController < AdministrativeController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  
    def index
      @recipes = Recipe.all
    end
  
    def show
    end
  
    def new
      @recipe = Recipe.new
    end
  
    def edit
    end
  
    def create
      @recipe = Recipe.new(recipe_params)
  
      respond_to do |format|
        if @recipe.save
          format.html { redirect_to administrative_recipes_path, notice: 'Receita criada com sucesso.' }
          format.json { render :show, status: :created, location: @recipe }
        else
          format.html { render :new }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @recipe.update(recipe_params)
          format.html { redirect_to administrative_recipes_path, notice: 'Receita atualizada com sucesso.' }
          format.json { render :show, status: :ok, location: @recipe }
        else
          format.html { render :edit }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @recipe.destroy
      respond_to do |format|
        format.html { redirect_to administrative_recipes_path, notice: 'Receita excluida com sucesso.' }
        format.json { head :no_content }
      end
    end
  
    private

      def set_recipe
        @recipe = Recipe.find(params[:id])
      end
  
      def recipe_params
        params.require(:recipe).permit(:name, :description, :price,
        ingredients_attributes: Ingredient.attribute_names.map(&:to_sym).push(:_destroy))
      end
  end
  

app/controllers/administrative_controller.rb
class AdministrativeController < ActionController::Base
    before_action :authenticate_admin!
    layout 'administrative'
    
    def index
    end
end

app/views/layouts/administrative/_footer.html.erb
<div class="footer">
    <div class="float-right">
        Versão 1.0.0 - setembro de 2019
    </div>
    <div>
        Desenvolvido por <a href="http://gtijr.com/" target='_blank'>GTi Jr</a> 
    </div>
</div>

app/views/layouts/administrative/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <%#= image_tag 'servita_logo.png', class: 'img-fluid' %>
      </li>
      <li>
        <%= link_to root_path do %>
          <i class="fa fa-home"></i> <span class="nav-label">Início</span>
        <% end %>
      </li>
      <li>
        <%= link_to administrative_admins_path do %>
          <i class="fa fa-user"></i> <span class="nav-label">Administradores</span>
        <% end %>
      </li>
      <li>
        <%= link_to administrative_recipes_path do %>
          <i class="fa fa-user"></i> <span class="nav-label">Exemplo Cocoon</span>
        <% end %>
      </li>
      <li>
          <%= link_to destroy_admin_session_path do %>
              <i class="fa fa-sign-out"></i> <span>Logout</span>
          <% end %>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/administrative/_topnavbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
              <span class="label label-primary" id='count-notifications'><i class="fa fa-user"></i>Perfil</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li>
              <div class="text-center">
                <%= current_admin.email%>
              </div>
            </li>
            <li>
                <div class="text-center link-block">
                  <%= link_to edit_admin_registration_path, class: "btn btn-warning" do %>
                      <strong>Alterar senha</strong>
                  <% end %>
                </div>
            </li>
          </ul>
        </li>
      </ul>
    </ul>
  </nav>
</div>